notifications:
    email:
        recipients:
            - dilawar.s.rajput@gmail.com
            - upi.bhalla@gmail.com
            - ray.shubhasis@gmail.com
            - hrani@ncbs.res.in


install:
    - wget http://download.opensuse.org/repositories/home:moose/xUbuntu_12.04/Release.key
    - sudo apt-key add - < Release.key  
    - sudo sh -c "echo 'deb http://download.opensuse.org/repositories/home:/moose/xUbuntu_12.04/ /' >> /etc/apt/sources.list.d/moose.list"
    - sudo apt-get -y update
    - sudo apt-get -y --force-yes install python-qt4 python-pip
    - sudo apt-get -y --force-yes install moose
    - sudo pip install python-libsbml

script:
    - # Making sure no python3 incompatible file.
    - python3 -m compileall -q .
    - python2 -m compileall -q .
    - python -c 'import moose'
    - cd _travis && ./find_scripts_to_run.sh && ./run_scripts.sh 
